version: '3'
services:
  nginx:
    image: rossifumax/nginx-4dvop
    ports:
      - "8080:8080"
  haproxy:
    image: rossifumax/haproxy-4dvop
    ports:
      - "80:80"
    depends_on:
      - nginx
